services:
    my_blog.post_finish_mail:
        class: My\BlogBundle\Mail\PostFinishMail
        arguments: [@mailer, @templating ]
    my_blog.post_service:
        class: My\BlogBundle\Service\PostService
        arguments: [@doctrine, @logger, @my_blog.post_finish_mail ]
